# Generated by Django 6.0 on 2026-01-07 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Found',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=500)),
                ('date', models.DateField()),
                ('location', models.CharField(max_length=120)),
                ('additional_identifiers', models.TextField(blank=True)),
                ('status', models.CharField(default='found', editable=False, max_length=10)),
                ('image', models.FileField(blank=True, upload_to='')),
                ('contact_type', models.CharField()),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
