# Generated by Django 6.0 on 2026-01-20 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('found', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='found',
            name='additional_identifiers',
        ),
    ]
