# Generated by Django 6.0 on 2025-12-30 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('found', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='found',
            name='status',
            field=models.CharField(default='found', editable=False, max_length=10),
        ),
    ]
