# Generated by Django 6.0 on 2025-12-30 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('found', '0002_found_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='found',
            old_name='date_found',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='found',
            old_name='location_found',
            new_name='location',
        ),
    ]
