# Generated by Django 6.0 on 2026-01-30 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('found', '0003_claim'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Claim',
        ),
    ]
