# Generated by Django 5.2 on 2025-12-27 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Found',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=500)),
                ('date_lost', models.DateField()),
                ('location_lost', models.CharField(max_length=120)),
                ('additional_identifiers', models.TextField(blank=True)),
                ('reward', models.CharField(blank=True)),
                ('image', models.FileField(blank=True, upload_to='')),
                ('contact_type', models.CharField()),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
