# Generated by Django 5.2 on 2025-12-27 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lost', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Found',
            new_name='Lost',
        ),
    ]
