# Generated by Django 6.0 on 2025-12-30 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lost', '0002_rename_found_lost'),
    ]

    operations = [
        migrations.AddField(
            model_name='lost',
            name='status',
            field=models.CharField(default='lost', editable=False, max_length=10),
        ),
        migrations.AlterField(
            model_name='lost',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
