# Generated by Django 6.0 on 2025-12-30 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lost', '0003_lost_status_alter_lost_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lost',
            old_name='date_lost',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='lost',
            old_name='location_lost',
            new_name='location',
        ),
    ]
