# Generated by Django 6.0 on 2025-12-31 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lost', '0004_rename_date_lost_lost_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lost',
            name='contact_type',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='lost',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='lost_images'),
        ),
    ]
